#ifndef WMO_WEATHER_CODES_H
#define WMO_WEATHER_CODES_H


typedef enum {
    WMO_CLEAR = 0,
    WMO_MAINLY_CLEAR = 1,
    WMO_PARTLY_CLOUDY = 2,
    WMO_OVERCAST = 3,

    WMO_FOG = 45,
    WMO_RIME_FOG = 48,

    WMO_DRIZZLE_LIGHT = 51,
    WMO_DRIZZLE_MODERATE = 53,
    WMO_DRIZZLE_DENSE = 55,
    WMO_FREEZING_DRIZZLE_LIGHT = 56,
    WMO_FREEZING_DRIZZLE_DENSE = 57,

    WMO_RAIN_LIGHT = 61,
    WMO_RAIN_MODERATE = 63,
    WMO_RAIN_HEAVY = 65,
    WMO_FREEZING_RAIN_LIGHT = 66,
    WMO_FREEZING_RAIN_HEAVY = 67,

    WMO_SNOW_LIGHT = 71,
    WMO_SNOW_MODERATE = 73,
    WMO_SNOW_HEAVY = 75,
    WMO_SNOW_GRAINS = 77,

    WMO_SNOW_SHOWERS_LIGHT = 85,
    WMO_SNOW_SHOWERS_HEAVY = 86,

    WMO_RAIN_SHOWERS_LIGHT = 80,
    WMO_RAIN_SHOWERS_MODERATE = 81,
    WMO_RAIN_SHOWERS_VIOLENT = 82,

    WMO_THUNDERSTORM = 95,
    WMO_THUNDERSTORM_HAIL_LIGHT = 96,
    WMO_THUNDERSTORM_HAIL_HEAVY = 99
} WeatherCode;



#endif